# -*- coding: utf-8 -*-
"""260319.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WfbmADrVfPF7N3oJp_nIdG8bqgcCp5Fp
"""

#문제. 숫자 입력 후, 그 숫자의 약수를 출력
# 내 답
n = int(input('숫자는 : '))
for i in range(1, n+1) :
   if n % i == 0 :
     print(i)

n = int(input()) # 문제 답
print("{}의 약수 : 1, ".format(n), end='')
for i in range(2, n) :
   if n % i == 0 :
    print("{}, ".format(i), end='')

print(n)

# {}, .format()을  사용하여 풀이
# 원하는 답 출력

n = int(input("입력 숫자 : ")) # 문제를 while 로 답했을 때

print("{}의 약수 : 1, ".format(n), end='')
i = 2

while i < n : # i != num 이 될 때도 있음
    if n % i == 0 :
        print("{}, ".format(i), end='')
    i = i +1

print(n)

"""업다운 코드 작성 문제




"""

import random

num = random.randint(1, 100)
print(num)

while True :
    rannum = int(input("숫자를 입력하세요 : "))
    if num == rannum :
        print("정답")
        break
    elif num > rannum :
        print("업")
    else :
        print("다운")

"""수업 시작_function

코드의 중복성 낮춤 : 반복적인 코딩을 할 때, 여러번 같은 코드를 안 써도 됨

재사용성 : 함수를 한번 만들어두면 여러곳에서 다시 쓸 수 있음
"""

def ab_value(num) : #function 예시1
    if num >= 0 :
        return num
    else :
        return -num

num = ab_value(2)
print(num)
print(ab_value(-4))

def greet(name, msg="Good morning") : # Default 인자 예시
    print("Hello", name + ', ' + msg)

greet("Kate")
greet("Bruce", "How do you do?")

# 2 keyword 인자
greet(name = "Bruce", msg = "How do you do?")
# 2 keyword 인자(out if order)
greet(msg = "How do you do?", name = "Bruce")
# 1 positional, 1 keyword
greet("Bruce", msg = "How do you do?")
# Error -> 처음 인자를 선언하면, 그 뒤에도 계속 해줘야 됨.
# greet(name = "Bruce", "How do you do?")

def greet(*names) : # Arbitary 인자 예시
    for name in names :
        print("Hello", name)

greet("Monica", "Luke", "Steve", "John")

"""재귀 : 함수가 자기 자신을 호출하는 것"""

def factorial(x) : # 재귀 예시1
    if x == 1 :
        return 1
    else :
        return (x * factorial(x-1))

num = 3
print("The factorial of", num, "is", factorial(num))

"""Lambda function(Anonymous) = 재귀 함수

lambda 키워드 사용, 일회성임,
호출하는 게 빠르다.
"""

double = lambda x : x * 2
print(double(5))

# 같은 식
#def double(x) :
#     return x * 2

"""lambda 예시와 lambda를 쓰지 않은 코드"""

my_list = [1, 5, 4, 6, 8, 11, 3, 12]
new_list = list(filter(lambda x: (x%2 == 0), my_list))

# new_list = []
#for val in my_list : ->  lambda 를 쓰지 않으면 이렇게 씀
#   if val%2 == 0:
#       new_list.append(val)

print(new_list)

list_1 = [2,3,4]
list_1 = list_1 + [5, 6, [1,2,3]]
list_2 = [2,3,4]
print(list_1)

new_list_2 = []
for val in list_2 :
    new_list_2.append(val * 2)
print(new_list_2)

#map(lambda x : x*2, list_2)
new_list_2 = list(map(lambda x:x*2, list_2))