# -*- coding: utf-8 -*-
"""260318.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10SpnkYHPtvb2HGjYWVC0HelQEGapxr0D
"""

#enumerate() 예제
str = 'cold'
list_enumerate = list(enumerate(str)) # 형변환이 되어 나타남(Explicit)
print('list(enumerate(str) = ', list_enumerate)

#character count
print('len(str) = ', len(str))

x1 = 5
y1 = 5
x2 = 'Hello'
y2 = 'Hello'
x3 = [1,2,3]
y3 = [1,2,3]
#항등 연산자 -> 동등한 값을 가지지만, 메모리 주소를 확인하는데 사용
#리터널은 동일한 주소를 가지지만, 리터널 모음은 다른 주소를 가짐
print(x1 is not y1)
print(x2 is y2)
print(x3 is y3)

def outer_function() : # Namespace 예제1
    # b : local
    b = 20
    def inner_func() :
        # c : nested local
        c = 30
        print(a)
    inner_func()
# a : global
a = 10
outer_function()

"""Namespace 는 변수의 적용 범위를 구분하여 사용함

function(local) < module(global(지역)) < built-in(전역)
"""

def outer_function() : #Namespace 예제2
    a = 20
    def inner_function() :
        a = 30
        print('a = ', a)
    inner_function()
    print('a = ', a)
a = 10
outer_function()
print('a = ', a)

def outer_function() : #Namespace 예제3
     global a
     a = 20

     def inner_function() :
        global a #moudle namespace
        a = 30
        print('a = ', a)
        inner_function() # global 로 인해 inner_funcion()안에 밑 두 줄을 넣어야 오류가 안남
        print('a = ', a)

a = 10
outer_function()
print('a = ', a)

num = 3 # if 예시
if num > 0 :
    print(num, "is a positive number")
print("This is always printed.")

num = -1
if num > 0 :
    print(num, "is a positive number")
print("This is also always printed")

num = 3 # if else 예시
if num >= 0 :
    print("Positive or Zero")
else :
    print("Negative number")

num = 3.4 # if elif else 예시

if num > 0 :
    print("Positive or Zero")
elif num == 0 :
    print("Zero")
else :
    print("Negative number")

# List of numbers / for loop 예제
numbers = [6, 5, 3, 8, 4, 2, 5, 4, 11]

# variable to store the sum
sum = 0

# iterate over the list
for val in numbers :
    sum = sum + val
print("the sum is", sum)

genre = ['pop', 'rock', 'jazz'] # for lop + rnage() 예시1
#in, len,__getitem__ 연산자 지원함
#iterate over the list using index
for i in range(len(genre)):
    print("I like", genre[i])

genre = [0, 1, 2] # for lop + rnage() 예시1-2
#in, len,__getitem__ 연산자 지원함
#iterate over the list using index
for i in range(len(genre)):
    print("I like", genre[i])

print(range(10)) # for loop + range() 예시2

print(list(range(10)))

print(list(range(2, 8)))

print(list(range(2, 20, 3)))

n = int(input("Enter n : ")) # While loop 예시

#initialize sum and counter
sum = 0
i = 1

while i <= n :
    sum = sum + i
    i = i +1   # update counter

# print the sum
print("The sum is", sum)

counter = 0 # While loop + else 예시, 많이 안 씀

while counter < 3 :
    print("Inside loop")
    counter = counter + 1
else :
    print("Inside else")

for val in "string" : # 강제적으로 멈추거나 건너뛰고 싶은 반복문 아래에 둬야 됨
    if val == "i" :
        break
        # continue
    print(val)
print("The end")